#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
                           
      ___           _ _     
     | __|__ _ _ __| (_)    
     | _/ -_) '_/ _` | |    
   __|_|\___|_| \__,_|_|    
  / __| ___ _ ___ _____ _ _ 
  \__ \/ -_) '_\ V / -_) '_|
  |___/\___|_|  \_/\___|_|  
                        
Brought to you by getferdi.com
Support our Open Collective at:
https://opencollective.com/getferdi
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults