#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
                           
       _____           _ _     
      |   __|___ ___ _| |_|    
      |   __| -_|  _| . | |    
      |__|  |___|_| |___|_|    
                           
                           
     _____                     
    |   __|___ ___ _ _ ___ ___ 
    |__   | -_|  _| | | -_|  _|
    |_____|___|_|  \_/|___|_|                    


Brought to you by getferdi.com
Support our Open Collective at:
https://opencollective.com/getferdi
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults