#!/usr/bin/with-contenv bash

# Display variables for troubleshooting
echo " "
echo "-------------------------------------"
echo " "
echo -e "Variables set:\\n\
NODE_ENV=${NODE_ENV}\\n\
DB_CONNECTION=${DB_CONNECTION}\\n\
DB_HOST=${DB_HOST}\\n\
DB_PORT=${DB_PORT}\\n\
DB_USER=${DB_USER}\\n\
DB_PASSWORD=${DB_PASSWORD}\\n\
DB_DATABASE=${DB_DATABASE}\\n\
IS_CREATION_ENABLED=${IS_CREATION_ENABLED}\\n\
CONNECT_WITH_FRANZ=${CONNECT_WITH_FRANZ}\\n"

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
	echo " "
	echo '**** [services.d] done ****'
fi

# create directory structure
mkdir -p /usr/src/app

# install ferdi-server if necessary
[[ -f /ferdi/ferdi.tar.gz ]] && \
 echo "**** Installing Ferdi-server ****" && \
 tar xf \
 	/ferdi/ferdi.tar.gz -C \
	/usr/src/app --strip-components=1 && \
 rm -rf \
    /ferdi && \
 chown -R abc:abc /usr/src/app	

# set ferdi-server status
echo " "
echo "**** Checking Ferdi-server settings ****"
if [ -f /config/config.txt ]; then
    sed -i "s/NODE_ENV=.*/NODE_ENV=${NODE_ENV}/g" /config/config.txt
    sed -i "s/IS_CREATION_ENABLED=.*/IS_CREATION_ENABLED=${IS_CREATION_ENABLED}/g" /config/config.txt
    sed -i "s/CONNECT_WITH_FRANZ=.*/CONNECT_WITH_FRANZ=${CONNECT_WITH_FRANZ}/g" /config/config.txt
    sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=${DB_CONNECTION}/g" /config/config.txt
    sed -i "s/DB_HOST=.*/DB_HOST=${DB_HOST}/g" /config/config.txt
    sed -i "s/DB_PORT=.*/DB_PORT=${DB_PORT}/g" /config/config.txt
    sed -i "s/DB_DATABASE=.*/DB_DATABASE=${DB_DATABASE}/g" /config/config.txt
    sed -i "s/DB_USER=.*/DB_USER=${DB_USER}/g" /config/config.txt
    sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/g" /config/config.txt
	rm /config/.env
    cp /config/config.txt /config/.env
elif [ ! -f /config/config.txt ]; then
    echo " " 
    echo "**** Generating .env file ****"	
    cp /defaults/.env.example /config/.env
	sed -i "s/NODE_ENV=.*/NODE_ENV=${NODE_ENV}/g" /config/.env
	sed -i "s/IS_CREATION_ENABLED=.*/IS_CREATION_ENABLED=${IS_CREATION_ENABLED}/g" /config/.env
	sed -i "s/CONNECT_WITH_FRANZ=.*/CONNECT_WITH_FRANZ=${CONNECT_WITH_FRANZ}/g" /config/.env
	sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=${DB_CONNECTION}/g" /config/.env
	sed -i "s/DB_HOST=.*/DB_HOST=${DB_HOST}/g" /config/.env
	sed -i "s/DB_PORT=.*/DB_PORT=${DB_PORT}/g" /config/.env
	sed -i "s/DB_DATABASE=.*/DB_DATABASE=${DB_DATABASE}/g" /config/.env
	sed -i "s/DB_USER=.*/DB_USER=${DB_USER}/g" /config/.env
	sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/g" /config/.env
	cp /config/.env /config/config.txt
fi

# update .env
if [ -f /usr/src/app/.env ]; then
	rm /usr/src/.env
	ln -s /config/.env /usr/src/app/.env
elif [ ! -f /usr/src/app/.env ]; then
	ln -s /config/.env /usr/src/app/.env
fi

# install adonisjs cli
echo " "
echo "**** Installing AdonisJS and deps ****"
cd /usr/src/app
echo " " 
npm i -g @adonisjs/cli

# install adonisjs dependencies
npm install

# setting the database helper
if [ "${DB_CONNECTION}" = "sqlite" ]; then
	echo " "
    echo "**** DB helper loaded ****"
  else npm i ${DB_CONNECTION} 
  echo " "
  echo "**** DB Helper loaded ****"
fi

# check for the database endpoint for 30 seconds
echo " "
echo "**** Checking DB endpoint ****"
END=$((SECONDS+30))
while [ ${SECONDS} -lt ${END} ] && [ "${DB_HOST} ${DB_PORT}" ];
	do
	/usr/bin/nc -z ${DB_HOST} ${DB_PORT} && \
	if [ ! -z "$(/usr/bin/nc -w1 ${DB_HOST} ${DB_PORT})" ];
		then
		[ ! -z "${RUN}" ] && break
		RUN="RAN"
		# we sleep here again due to first run init on DB containers
		[ ! -f /dbwait.lock ] && sleep 5
	else
		sleep 1
	fi
	sleep 1
done

# source the .env file
source .env

# database migration
echo " "
echo "**** Run DB migration ****"
adonis migration:run --force

# Create APP key if needed
if [ ! -f "/config/FERDI_APP_KEY.txt" ];
	then
	echo " "
	echo "**** Generating Ferdi-server app key for first run ****"
    adonis key:generate
	source .env
	echo $APP_KEY > /config/FERDI_APP_KEY.txt
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
	sed -i "s/APP_KEY=/APP_KEY=$APP_KEY/g" /config/config.txt
elif [ -f "/config/FERDI_APP_KEY.txt" ];
	then
	echo " "
	echo "**** App Key found ****"
	APP_KEY=$(cat /config/FERDI_APP_KEY.txt)
	sed -i "s/APP_KEY=.*/APP_KEY=$APP_KEY/g" /config/config.txt
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
fi

# set permissions
chown -R abc:abc \
	/config \
	/usr/src/app

# set lockfile to avoid DB waits for this specific container
touch /dbwait.lock

# start server
echo " "
echo "**** Starting Ferdi-server ****"
adonis serve --dev